# Generated by Django 2.2.19 on 2022-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220824_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
